import ConvexUniformHoneycombs.TwoTier
import ConvexUniformHoneycombs.Tails
import ConvexUniformHoneycombs.Icosahedral
import ConvexUniformHoneycombs.Forcing
import ConvexUniformHoneycombs.Periodization
